# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b58c188d8be16a8d552a581a398f0f1d62295ca1a1967bdc4d0c762a3f5c2cf22c51d227744440cbec729a8dee2b98aba21224e085a8f06f2b07e63813fb694

test:
  secret_key_base: a5e3586e346a57aaa44b3afceb8f9782506b9c87129dafb08d57aedcedbeceea9faa33f5eff1c5fc82c0b6c71bdb9b2896e99913da9ee006443fb9b1da564032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
